**LEAP YEAR OR NOT**

In [1]:
year=int(input("Enter a year: "))

if (year%4==0 and year%100!=0) or year%400==0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

Enter a year: 2002
2002 is not a leap year


**MULTIPLICATION NUMBER**

In [2]:
x=int(input("Enter a multiplication number:"))

for i in range(1, 13):
    print(x,"X",i,"=",x*i)

Enter a multiplication number:5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
5 X 11 = 55
5 X 12 = 60


**PRIME OR NOT**

In [3]:
x=int(input("Enter a number:"))

if x==1:
    print(x,"is not a prime number")
else:
    for i in range(2,x):
        if x%i==0:
            print(x,"is not a prime number")
            break
    else:
        print(x,"is a prime number")

Enter a number:5
5 is a prime number


**PROGRAM WITH SWITCH CASE**

In [4]:
def func(x):
    switcher = {
        1: str.upper(),
        2: str.lower(),
        3: str.isupper(),
        4: str.islower(),
        5: str.replace('INTELLIgence','Neural Network'),
        6: str.startswith('T'),
        7: str.endswith('e'),
        8: str.capitalize(),
        9: str.swapcase()
    }
    return switcher.get(x,"Invalid Number")

str=input("Enter a string: ")

while True:
    print("1.Convert the input string into UpperCase")
    print("2.Convert the input string into LowerCase")
    print("3.Check whether all the character of the input string are in UpperCase")
    print("4.Check whether all the character of the input string are in LowerCase")
    print("5.Replace string 'INTELLIgence' by 'Neural Network'")
    print("6.Check whther the given string starts with 'T'")
    print("7.Check whether the given string ends with 'e'")
    print("8.Convert the first letter of the input string into caital letter")
    print("9.Convert the LowerCase characters to UpperCase and ViceVersa")
    print("10.Exit")
    print("-------------------")
    x=int(input("Choose any Option: "))
    if(x==10):
        break
    print (func(x))

Enter a string: RADHAKRISHNA
1.Convert the input string into UpperCase
2.Convert the input string into LowerCase
3.Check whether all the character of the input string are in UpperCase
4.Check whether all the character of the input string are in LowerCase
5.Replace string 'INTELLIgence' by 'Neural Network'
6.Check whther the given string starts with 'T'
7.Check whether the given string ends with 'e'
8.Convert the first letter of the input string into caital letter
9.Convert the LowerCase characters to UpperCase and ViceVersa
10.Exit
-------------------
Choose any Option: 1
RADHAKRISHNA
1.Convert the input string into UpperCase
2.Convert the input string into LowerCase
3.Check whether all the character of the input string are in UpperCase
4.Check whether all the character of the input string are in LowerCase
5.Replace string 'INTELLIgence' by 'Neural Network'
6.Check whther the given string starts with 'T'
7.Check whether the given string ends with 'e'
8.Convert the first letter of the i

**STUDENT ADVISOR BOT**

In [6]:
print("Hi I am student advisor chat Bot.\nMay I know your name?")
str=input();
print("Thank You", str);
print("I am here to explore you about the core courses required for the specialization's offered in KL University. Cse Dept")
dic1={"Global certication":"Professional Scrum Master","Core Course in 1st Sem":"Software Engneering"}
dic2={"Global certication":"None","Core Course in 1st Sem":"None"}
dic3={"Global certication":"Linux Essential(010-160)","Core Course in 1st Sem":"Operating Systems"}
dic4={"Global certication":"Unity Developer Advance Certification","Core Course in 1st Sem":"Enterprise Programming"}
dic5={"Global certication":"ETHEREUM Developer Advance Certification","Core Course in 1st Sem":"Computer Networks"}
dic6={"Global certication":"PCAP|CertifiedAssociatePythonProgramming","Core Course in 1st Sem":"AI & Mathematical Programming"}
dic7={"Global certication":"C100DEV:MangoDB certified DeveloperAssociate","Core Course in 1st Sem":"Data Base Managements System"}
dic8={"Global certication":"None","Core Course in 1st Sem":"None"}

def func(x):
    switcher = {
        1: dic1,
        2: dic2,
        3: dic3,
        4: dic4,
        5: dic5,
        6: dic6,
        7: dic7,
        8: dic8
    }
    return switcher.get(x,False);

while(True):
    print("1. Software Modelling & DevOps\n2. Internet of Things\n3. Cloud & Edge Computing\n4. Graphics, Gaming &UX Design")
    print("5. Cyber Security & Blockchain Technology\n6. Artificial Intelligence & Intelligence Process Automation")
    print("7. Data Science & Big Data Analytics\n8. Computer Communications\n9.Exit\n");
    print("These are the specialization's offered by KL CSE.Choose any specialization.(select any option)")
    x=int(input("Choose any option: "));
    if(func(x)==False):
        break;
    else:
        print(func(x));

Hi I am student advisor chat Bot.
May I know your name?
RADHA
Thank You RADHA
I am here to explore you about the core courses required for the specialization's offered in KL University. Cse Dept
1. Software Modelling & DevOps
2. Internet of Things
3. Cloud & Edge Computing
4. Graphics, Gaming &UX Design
5. Cyber Security & Blockchain Technology
6. Artificial Intelligence & Intelligence Process Automation
7. Data Science & Big Data Analytics
8. Computer Communications
9.Exit

These are the specialization's offered by KL CSE.Choose any specialization.(select any option)
Choose any option: 6
{'Global certication': 'PCAP|CertifiedAssociatePythonProgramming', 'Core Course in 1st Sem': 'AI & Mathematical Programming'}
1. Software Modelling & DevOps
2. Internet of Things
3. Cloud & Edge Computing
4. Graphics, Gaming &UX Design
5. Cyber Security & Blockchain Technology
6. Artificial Intelligence & Intelligence Process Automation
7. Data Science & Big Data Analytics
8. Computer Communications
9

**CHAT BOT TO PRINT DAYS, MIN, SEC FROM OUR BIRTH DAY**

In [9]:
from datetime import date

print("Hello I am Chatty Here to help You")
print("May I know your good name?")
str=input()
print("Hello",str)
choice=input("Do you want to know your age in years,days,hours,minutes,sec you live till now?")
if(choice.lower()=="yes" or choice.lower() =="y"):        
    day=int(input("Date: "))
    month=int(input("Month: "))
    year=int(input("Year: "))
    dob=date(year,month,day)
    now=date.today()
    if(now.month<dob.month):
        print(now.year-dob.year-1,"years")
    elif(now.month==dob.month and now.day<dob.day):
        print(now.year-dob.year-1,"years")
    else:
        print(now.year-dob.year,"years")
    diff=now-dob
    print(diff.days,"days")
    print(diff.days*24,"hours")
    print(diff.days*24*60,"minutes")
    print(diff.days*24*60*60,"seconds")
    color=input("Can I know your favourite Color:")
    if(color.upper()=="BLUE"):
        print("Blue is the color of sea and sky. It is often associated with depth and stability")
    if(color.upper()=="RED"):
        print("Red is the color of blood")
    if(color.upper()=="GREEN"):
        print("Green is the color of nature")
    if(color.upper()=="PINK"):
        print("Pink, a delicate color that means sweet,charming")
    print("It's time to say bye")
    print("I hope you enjoy well")
else:
    print("Byee")

Hello I am Chatty Here to help You
May I know your good name?
radha
Hello radha
Do you want to know your age in years,days,hours,minutes,sec you live till now?yes
Date: 20
Month: 6
Year: 2002
19 years
7004 days
168096 hours
10085760 minutes
605145600 seconds
Can I know your favourite Color:blue
Blue is the color of sea and sky. It is often associated with depth and stability
It's time to say bye
I hope you enjoy well


**MIN AND MAX IN 2D ARRAY**

In [10]:
x=list(map(int,input().split()))
r=x[0]
c=x[1]

mi=list()

for i in range(r):
    a=list(map(int,input().split()))
    mi.append(min(a))

print("Max=",max(mi))

4 2
2 5
3 7
1 3
4 0
Max= 3


**WATER JUG PROBLEM WITH CONTAINER1 CAPACITY=5 AND CONTAINER2 CAPACITY=4**

In [14]:
print("Water Jug Problem")
x = int(input('Enter x:'))
y = int(input('Enter y:'))
while True:
    rule = int(input('Enter the rule number: '))
    if(rule == 1):
        if x<5:
            x=5
    if(rule == 2):
        if y<4:
            y=4
    if(rule == 3):
        if x>0:
            x=0
    if(rule == 4):
        if y>0:
            y=0
    if(rule == 5):
        if x+y>=5 and y>0:
            x,y = 5,y-(5-x)
    if(rule == 6):
        if x+y>4 and y>0:
            x,y = x-(4-y),4
    if(rule == 7):
        if x+y<=5 and y>0:
            x,y = x+y,0
    if(rule == 8):
        if x+y<=4 and y>0:
            x,y = 0,x+y
    print('X=',x)
    print('Y=',y)
    if(x == 2):
        print("The result is goal state.")
        break

Water Jug Problem
Enter x:0
Enter y:0
Enter the rule number: 2
X= 0
Y= 4
Enter the rule number: 7
X= 4
Y= 0
Enter the rule number: 2
X= 4
Y= 4
Enter the rule number: 5
X= 5
Y= 3
Enter the rule number: 3
X= 0
Y= 3
Enter the rule number: 7
X= 3
Y= 0
Enter the rule number: 2
X= 3
Y= 4
Enter the rule number: 5
X= 5
Y= 2
Enter the rule number: 3
X= 0
Y= 2
Enter the rule number: 7
X= 2
Y= 0
The result is goal state.


**WATER JUG PROBLEM WITH DYNAMIC CAPACITIES AND 3 GALLONS**

In [16]:
print("**WATER JUG PROBLEM**") 
a=int(input("enter a value:")) 
b=int(input("enter b value:")) 
c=int(input("enter c value")) 
#GIVE CAPACITY OF CONTAINERS 
x=int(input("Enter 1st Container Capacity")); 
y=int(input("Enter 2nd container Capacity")); 
z=int(input("Enter 3rd container Capacity")); 
#GIVE GOAL STATE 
g=int(input("Enter the Goal State Capacity:")); 
while True: 
  ruleno=int(input("enter the ruleno:")) 
  if(ruleno==1): 
    if a<x : 
      a=x 
  if(ruleno==2): 
    if a+b<x and c>0 :
      a,b,c=a,a-c,y-a 
  if(ruleno==3): 
    if a==x and b+c==0:
      a,b,c=x-y,y,c 
  if(ruleno==4): 
    if a+b==x and c==0:
      a,b,c=a-z,b,z 
  if(ruleno==5): 
    if a+b==y and c>0:
      a,b,c=y,x-(b+c),c 
  if(ruleno==6): 
    if a+b>y and c>0:
      a,b,c=a+b,y-b,c; 
  if(ruleno==7): 
    if a+b<y and c>0:
      a,b,c=a,y,c-b 
  if(ruleno==8): 
    if a+b<x and b==0:
      a,b,c=a,c,x-(a+c) 
  if(ruleno==9): 
    if b+c<=x and c==0:
      a,b,c=y-2*(x-y),y,x-y 
  print("A=",a) 
  print("B=",b) 
  print("C=",c) 
  if(a==g or b==g or c==g): 
    print("The goal state is reached") 
    break 


**WATER JUG PROBLEM**
enter a value:0
enter b value:0
enter c value0
Enter 1st Container Capacity12
Enter 2nd container Capacity8
Enter 3rd container Capacity5
Enter the Goal State Capacity:6
enter the ruleno:1
A= 12
B= 0
C= 0
enter the ruleno:3
A= 4
B= 8
C= 0
enter the ruleno:9
A= 0
B= 8
C= 4
enter the ruleno:5
A= 8
B= 0
C= 4
enter the ruleno:8
A= 8
B= 4
C= 0
enter the ruleno:4
A= 3
B= 4
C= 5
enter the ruleno:7
A= 3
B= 8
C= 1
enter the ruleno:6
A= 11
B= 0
C= 1
enter the ruleno:8
A= 11
B= 1
C= 0
enter the ruleno:4
A= 6
B= 1
C= 5
The goal state is reached


**BREADTH FIRST SEARCH**

In [21]:
graph = {
    
  'A' : ['B','C','D'],
  'B' : ['E', 'F'],
  'C' : [],
  'D' : ['G','H','I'],
  'E' : ['J'],
  'F' : ['K'],
  'G' : ['L'],
  'H' : [],
  'I' : [],
  'J' : [],
  'K' : [],
  'L' : [],
}

visited = []
queue = []    

def bfs(visited, graph, node):
  visited.append(node)
  queue.append(node)

  while queue:
    s = queue.pop(0)
    print (s, end = " ")

    for neighbour in graph[s]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

bfs(visited, graph, 'A')

A B C D E F G H I J K L 

**DEPTH FIRST SEARCH**

In [23]:
graph = {
    'A' : ['B','C'],
    'B' : ['D', 'E'],
    'C' : ['F','G'],
    'D' : ['H','I'],
    'E' : ['J'],
    'F' : ['K'],
    'G' : ['M'],
    'H' : [],
    'I' : [],
    'J' : [],
    'K' : [],
    'M' : [],
    
}

visited = set() 

def dfs(visited, graph, node):
    if node not in visited:
        print (node,end=" ")
        visited.add(node)
        for neighbour in graph[node]:
            dfs(visited, graph, neighbour)

dfs(visited, graph, 'A')

A B D H I E J C F K G M 

**IDDFS**

In [24]:
graph = {
    'A' : ['H','B'],
    'B' : ['C'],
    'C' : ['D'],
    'D' : [],
    'E' : [],
    'F' : [],
    'G' : [],
    'H' : ['G','I'],
    'I' : ['F','E']
}
root = 'A'
goal = 'D'

def IDDFS(start, goal):

    depth = 0
    while True: 

        print()
        print("Iteration at Level - ",depth)
        result = dfs(start, goal, depth)
        if result == goal:
            print()
            print("---Found Goal  State ---")
            print("Result:",goal,end = ' ')
            print("Goal:",goal)
            break
        depth = depth + 1
        
def dfs(node, goal, depth):

    print(node,end=' ')

    if depth == 0 and node == goal:
        return node
    elif depth > 0:
        for i in graph[node]:
            OneMoreTest = dfs(i, goal, depth - 1)
            if OneMoreTest == goal:
                return goal
IDDFS(root,goal)


Iteration at Level -  0
A 
Iteration at Level -  1
A H B 
Iteration at Level -  2
A H G I B C 
Iteration at Level -  3
A H G I F E B C D 
---Found Goal  State ---
Result: D Goal: D


**BI-DIRECTIONAL**

In [26]:
graph = {
    1 : [4],
    2 : [4],
    3 : [6],
    4 : [8],
    5 : [6],
    6 : [8],
    8 : [9],
    9 : [10],
    10: [9],
    11: [10],
    12: [10],
    13: [11],
    14: [11],
    15: [12],
    16: [12]
}
s_closed = []
s_opened = []
d_closed = []
d_opened = []

def bfs(graph,opened,closed):
    if opened:
        n = opened.pop(0)
        closed.append(n)
        for neighbour in graph[n]:
            if neighbour not in opened and neighbour not in closed:
                opened.append(neighbour)

def BidiSearch(graph,s,t):    
    s_opened.append(s)
    d_opened.append(t)
    while (s_opened and d_opened):
        bfs(graph,s_opened,s_closed)
        bfs(graph,d_opened,d_closed)
        if(any(x in s_closed for x in d_closed)):
            path = s_closed
            path.extend(d_closed[::-1])
            path = list(dict.fromkeys(path))
            print(" Path is: ",path,end=" ")
            return 1
    return 0

res = BidiSearch(graph,1,16)
if res == 0:
    print('No path from source to destination.')

 Path is:  [1, 4, 8, 9, 10, 12, 16] 

**A* ALGORITHM**

In [27]:
class Node:
    def __init__(self,f,h,g,curr_position,parent):
        self.parent = parent
        self.position = curr_position
        
        self.g = g
        self.h = h
        self.f = g+h
maze = [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

start = [0, 0]
end = [7 , 6]

h = [0.0]*10

for i in range(10):
    h[i] = [0]*10
def generate_h_value(h):
    for i in range(0,10):
        for j in range(0,10):
            h[i][j]=abs(end[0]-i)+abs(end[1]-j)

opened = []
node = Node(h[start[0]][start[1]]+0,h[start[0]][start[1]],0,start,'NA');
opened.append(node)

closed = []

neighbors = []
def isSafe(maze,x,y):
    if x >= 0 and x < 10 and y >=0 and y < 10 and maze[x][y] == 0:
        return True
    return False

def next_state(l):
    x = l[0]
    y = l[1]
    if isSafe(maze,x + 1,y) == True:
        neighbors.append([x+1,y])
    if isSafe(maze,x,y + 1) == True:
        neighbors.append([x,y+1])
    if isSafe(maze,x - 1,y) == True:
        neighbors.append([x - 1,y])
    if isSafe(maze,x,y-1) == True:
        neighbors.append([x,y-1])
    if isSafe(maze,x-1,y-1) == True:
        neighbors.append([x-1,y-1])
    if isSafe(maze,x+1,y-1) == True:
        neighbors.append([x+1,y-1])
    if isSafe(maze,x-1,y+1) == True:
        neighbors.append([x-1,y+1])
    if isSafe(maze,x+1,y+1) == True:
        neighbors.append([x+1, y+1])
    

generate_h_value(h)

while opened:
    best_node = opened[0]
    best_node_index = 0
    for index,item in enumerate(opened):
        if item.f < best_node.f:
            best_node = item
            best_node_index = index
    
    opened.pop(best_node_index)
    closed.append(best_node)
    
    if best_node.position == end:
        break
    next_state(best_node.position)
    for node in neighbors:
        flag = 0
        child = Node(h[node[0]][node[1]]+best_node.g+1,h[node[0]][node[1]],best_node.g+1,node,best_node)
        for index,i in enumerate(closed):
            if child.position == i.position and child.g <= i.g:
                i.f = child.f
                i.h = child.h
                i.g = child.g
                i.position = child.position
                i.parent = child.parent
                flag = 1
                break
        if flag == 1:
            continue
        for index,i in enumerate(opened):
            if child.position == i.position and child.g <= i.g:
                i.f = child.f
                i.h = child.h
                i.g = child.g
                i.position = child.position
                i.parent = child.parent
                flag = 1
                break
        if flag == 0:
            opened.append(child)
        
for index,i in enumerate(closed):
        print(i.position)

[0, 0]
[1, 1]
[2, 2]
[3, 3]
[4, 3]
[5, 4]
[6, 5]
[7, 6]


**SYSTEM TRIES TO REACH AND GENERATE THE SENTENCE HELLO, WORLD!**

In [28]:
import random
import string
def solution(length=13):
  return [random.choice(string.printable) for _ in range(length)]
def hello(sol):
  target = list("Hello, World!")
  diff = 0
  for i in range(len(target)):
    s = sol[i]
    g = target[i]
    diff += abs(ord(s) - ord(g))
  return diff
def mutate(sol):
  index = random.randint(0, len(sol) - 1)
  sol[index] = random.choice(string.printable)
best = solution()
best_score = hello(best)
while True:
  print('Best score so far', best_score, 'Solution', "".join(best))
  if best_score == 0:
    break
  new = list(best)
  mutate(new)
  score = hello(new)
  if hello(new) < best_score:
    best = new
    best_score = score

Best score so far 376 Solution zvYTg9trhnRHf
Best score so far 376 Solution zvYTg9trhnRHf
Best score so far 376 Solution zvYTg9trhnRHf
Best score so far 376 Solution zvYTg9trhnRHf
Best score so far 376 Solution zvYTg9trhnRHf
Best score so far 376 Solution zvYTg9trhnRHf
Best score so far 336 Solution zvYTg9trhnRH>
Best score so far 332 Solution zvYTg9trhnRH:
Best score so far 296 Solution zvYTg9PrhnRH:
Best score so far 284 Solution zvYTg9PrhnRt:
Best score so far 278 Solution zvYTg9PrnnRt:
Best score so far 278 Solution zvYTg9PrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 266 Solution zvYTg9DrnnRt:
Best score so far 257 Solution zvYTg9DrnnR]:
Best score

**MINIMAX ALGORITHM**

In [29]:
#minmax
import numpy as np
class Game_Tree:

  succs=dict(A=dict(a1='B',a2='C'),
             B=dict(b1='D',b2='E'),
             C=dict(c1='F',c2='G'),
             D=dict(d1='D1',d2='D2'),
             E=dict(e1='E1',e2='E2'),
             F=dict(f1='F1',f2='F2'),
             G=dict(g1='G1',g2='G2'))
  utils=dict(D1=2,D2=5,E1=11,E2=4,F1=14,F2=15,G1=3,G2=4)

  def actions(self,state):
    return list(self.succs.get(state,{}).keys())
  
  def result(self,state,move):
    return self.succs[state][move]

  def utility(self,state,player):
    if player=='MAX':
      return self.utils[state]
    else:
      return -self.utils[state]
  
  def terminal_test(self,state):
    return state not in ('A','B','C','D','E','F','G')

  def to_move(self,state):
    return 'MIN' if state in 'BC' else 'MAX'
def minmax_decision(state,game):
  player=game.to_move(state)
  def max_value(state):
    if game.terminal_test(state):
      return game.utility(state,player)
    v=-np.inf
    for a in game.actions(state):
      v=max(v,min_value(game.result(state,a)))
    return v
  
  def min_value(state):
    if game.terminal_test(state):
      return game.utility(state,player)
    v=np.inf
    for a in game.actions(state):
      v=min(v,max_value(game.result(state,a)))
    return v
  
  v=-np.inf
  for a in game.actions(state):
    v=max(v,min_value(game.result(state,a)))
  return v
state='A'
game=Game_Tree()
print(minmax_decision(state,game))

5


**ALPHA BETA PRUNING**

In [30]:
#alpha beta pruning
import numpy as np 
 
class Game_Tree: 
  succs=dict(A=dict(a1='B',a2='C',a3='D'), 
             B=dict(b1='E',b2='F'), 
             C=dict(c1='G',c2='H',c3='I'), 
             D=dict(d1='J',d2='K'), 
             E=dict(e1='E1',e2='E2'), 
             F=dict(f1='F1',f2='F2'), 
             G=dict(g1='G1',g2='G2'), 
             H=dict(h1='H1',h2='H2'), 
             I=dict(i1='I1',i2='I2'), 
             J=dict(j1='J1',j2='J2'), 
             K=dict(k1='K1',k2='K2')) 
  utils=dict(E1=4,E2=3,F1=6,F2=4,G1=2,G2=1,H1=9,H2=5,I1=3,I2=1,J1=5,J2=4,K1=7,K2=5) 
  initial='A' 
 
  def actions(self,state): 
    return list(self.succs.get(state,{}).keys())
  def result(self,state,move): 
    return self.succs[state][move]   
  def utility(self,state,player): 
    if player=='MAX':
      return self.utils[state]     
    else:       
      return -self.utils[state]   
  def terminal_test(self,state):
    return state not in('A','B','C','D','E','F','G','H','I','J','K')   
  def to_move(self,state):     
    return 'MIN' if state in 'BCD' else 'MAX' 
p=0 
alpha=-np.inf 
beta=np.inf 
def alpha_beta_search(state,game):   
  player=game.to_move(state) 
 
  #Functions used by alpha_beta   
  def max_value(state,alpha,beta):   
      global p     
      if game.terminal_test(state):       
        return game.utility(state,player)     
      v=-np.inf     
      for a in game.actions(state):      
        v=max(v,min_value(game.result(state,a),alpha,beta))       
        if v>=beta:         
          p=p+1 
          return v       
        alpha=max(alpha,v) 
      return v 
    
  def min_value(state,alpha,beta): 
      global p     
      if game.terminal_test(state):       
        return game.utility(state,player)     
      v=np.inf     
      for a in game.actions(state): 
        v=min(v,max_value(game.result(state,a),alpha,beta))       
        if v<=alpha:         
          p=p+1 
          return v       
        beta=min(beta,v) 
      return (v) 
    
  #Body of alpha_beta_search 
  global alpha   
  global beta   
  best_action=None   
  for a in game.actions(state):     
    v=min_value(game.result(state,a),alpha,beta)     
    if v > alpha:       
      alpha=v       
      best_action=a     
    else: 
      beta=v 
  return (v) 
state='A' 
game=Game_Tree() 
print("Result- ",alpha_beta_search(state,game)) 
print("Times pruned- ",p) 
print("Alpha- ",alpha) 
print("Beta- ",beta) 

Result-  5
Times pruned-  4
Alpha-  5
Beta-  2


**CONSTRAINT SATISFACTION PROBLEM**

**MAP COLORING**

In [31]:
#You have tocolor a map with different colors where no two neighboring regions can have the same color. Assume that you have 5 colors red, blue, green,yellow and pink.Write an efficient python code to color the regions in the following map.
colors=["Red","Blue","Green","Yellow","Pink"]

states=['AndhraPradesh','Karnataka','Tamilnadu','Kerala','MadhyaPradesh','Odisha','Telangana','Chhattisgarh','Maharastra']

neighbours={}

neighbours['AndhraPradesh']=['Karnataka','Tamilnadu','Odisha','Telangana']
neighbours['Karnataka']=['AndhraPradesh','Tamilnadu','Kerala','Telangana','Maharastra']
neighbours['Tamilnadu']=['AndhraPradesh','Karnataka','Kerala']
neighbours['Kerala']=['Karnataka','Tamilnadu']
neighbours['Telangana']=['Karnataka','Odisha','Chhattisgarh','Maharastra','AndhraPradesh']
neighbours['Maharastra']=['MadhyaPradesh','Karnataka','Chhattisgarh','Telangana']
neighbours['MadhyaPradesh']=['Maharastra','Chhattisgarh']
neighbours['Chhattisgarh']=['Maharastra','Odisha','Telangana','MadhyaPradesh']
neighbours['Odisha']=['Chhattisgarh','AndhraPradesh','Telangana']


colors_of_states={}
def promising(state,color):
  for neighbour in neighbours.get(state):
    color_of_neighbour = colors_of_states.get(neighbour)
    if color_of_neighbour==color:
      return False
  
  return True
def get_color_for_state(state):
  for color in colors:
    if(promising(state,color)):
      return color
def main():
  for state in states:
    colors_of_states[state]=get_color_for_state(state)

  print(colors_of_states)
main()

{'AndhraPradesh': 'Red', 'Karnataka': 'Blue', 'Tamilnadu': 'Green', 'Kerala': 'Red', 'MadhyaPradesh': 'Red', 'Odisha': 'Blue', 'Telangana': 'Green', 'Chhattisgarh': 'Yellow', 'Maharastra': 'Pink'}


In [33]:
#constraint statsfaction problem
def isMagicSquare(mat) :
    s = 0
    for i in range(0,R):
        s = s + mat[i][i]
    
    s2 = 0
    for i in range(0,R):
        s2 = s2 + mat[i][R-i-1]
    if(s!=s2):
        return False
    
    for i in range(0,R):
        rowSum = 0;
        for j in range(0,R):
            rowSum += mat[i][j]
        if(rowSum != s):
            return False
        
    for i in range(0,R):
        colSum = 0
        for j in range(0,R):
            colSum += mat[j][i]
        if(s != colSum):
            return False
    return True


R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 

# Initialize matrix 
mat = [] 
print("Enter the entries rowwise:") 

# For user input 
for i in range(R):		 # A for loop for row entries 
	a =[] 
	for j in range(C):	 # A for loop for column entries 
		a.append(int(input())) 
	mat.append(a) 

if(isMagicSquare(mat)) :
    print("Magic Square")
else :
    print("Not a magic Square")

Enter the number of rows:3
Enter the number of columns:3
Enter the entries rowwise:
1
3
6
7
2
5
8
9
7
Not a magic Square


**COST FUNCTION AND IDEA COST FUNCTION IN 8-PUZZLE PROBLEM**

In [34]:
#cost function and idea cost function in 8-puzzle problem
import math 
def minimax (curDepth, nodeIndex,maxTurn, scores,targetDepth): 
      # base case : targetDepth reached       
      if (curDepth == targetDepth):           
        return scores[nodeIndex] 
      if (maxTurn): 
        return max(minimax(curDepth + 1,nodeIndex*2,False,scores,targetDepth),minimax(curDepth + 1, nodeIndex * 2 + 1,False, scores, targetDepth))  
      else: 
        return min(minimax(curDepth + 1,nodeIndex * 2,True, scores, targetDepth),minimax(curDepth + 1, nodeIndex * 2 + 1,True, scores, targetDepth)) 
 
# Driver code 
scores = [3, 5, 2, 9, 12, 5, 23, 23] 
treeDepth = math.log(len(scores),2) 
print("The optimal value is : ", end = "") 
print(minimax(0, 0, True, scores, treeDepth)) 

The optimal value is : 12


In [41]:
import numpy as np  
import random 
from time import sleep 
# Creates an empty board 
def create_board(): 
  return(np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])) 
# Check for empty places on board 
def possibilities(board): 
  l = []    
  for i in range(len(board)):      
    for j in range(len(board)): 
        if board[i][j] == 0:
          l.append((i, j))
          return(l) 

# Select a random place for the player  
def random_place(board, player):     
  selection = possibilities(board)     
  current_loc = random.choice(selection)     
  board[current_loc] = player     
  return(board) 
 
# Checks whether the player has three # of their marks in a horizontal row 
def row_win(board, player):
  for x in range(len(board)):
    win = True
  for y in range(len(board)):
    if board[x, y] != player:
      win = False
      continue
    if win == True:
      return(win)
  return(win)

# Checks whether the player has three # of their marks in a vertical row 
def col_win(board, player):
  for x in range(len(board)):
    win = True
    for y in range(len(board)):
      if board[y][x] != player:
        win = False
        continue
    if win == True:
      return(win)
  return(win)  

# Checks whether the player has three # of their marks in a diagonal row 
def diag_win(board, player): 
  win = True
  y = 0
  for x in range(len(board)):
    if board[x, x] != player:
      win = False
  if win:
    return win
  win = True    
  if win:      
    for x in range(len(board)):        
      y = len(board) - 1 - x        
      if board[x, y] != player:
        win = False    
  return win 
 
# Evaluates whether there is # a winner or a tie 
def evaluate(board):
  winner = 0
  for player in [1, 2]:
    if (row_win(board, player) or col_win(board,player) or diag_win(board,player)):
      winner = player
  if np.all(board != 0) and winner == 0:
    winner = -1   
  return winner 
 
# Main function to start the game 
def play_game():   
  board, winner, counter = create_board(), 0, 1   
  print(board)   
  sleep(2)

  while winner == 0:
    for player in [1, 2]:
      board = random_place(board, player)
      print("Board after",counter,"move") 
      print(board)       
      sleep(2)       
      counter += 1       
      winner = evaluate(board)        
      if winner != 0:         
        break   
  return(winner)   
    
# Driver Code 
print("Winner is:",play_game()) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 2 0]
 [0 0 0]
 [0 0 0]]
Board after 3 move
[[1 2 1]
 [0 0 0]
 [0 0 0]]
Board after 4 move
[[1 2 1]
 [2 0 0]
 [0 0 0]]
Board after 5 move
[[1 2 1]
 [2 1 0]
 [0 0 0]]
Board after 6 move
[[1 2 1]
 [2 1 2]
 [0 0 0]]
Board after 7 move
[[1 2 1]
 [2 1 2]
 [1 0 0]]
Winner is: 1


**SUDOKO | BACKTRACKING**

In [42]:
#sudoko | Backtracking
SIZE=9 
matrix = [ 
 [6,5,0,8,7,3,0,9,0], 
 [0,0,3,2,5,0,0,0,8], 
 [9,8,0,1,0,4,3,5,7], 
 [1,0,5,0,0,0,0,0,0], 
 [4,0,0,0,0,0,0,0,2], 
 [0,0,0,0,0,0,5,0,3], 
 [5,7,8,3,0,1,0,2,6], 
 [2,0,0,0,4,8,9,0,0], 
 [0,9,0,6,2,5,0,8,1]] 
 
#function to print sudoku 
def print_sudoku():  
  for i in matrix:
    print (i) 
 
#function to check if all cells are assigned or not 
#if there is any unassigned cell 
#then this function will change the values of 
#row and col accordingly 
def number_unassigned(row, col):
  num_unassign = 0  
  for i in range(0,SIZE):    
    for j in range (0,SIZE):       
      #cell is unassigned       
      if matrix[i][j] == 0: 
        row = i         
        col = j         
        num_unassign = 1         
        a = [row, col, num_unassign]         
        return a  
  a = [-1, -1, num_unassign]  
  return a 
#function to check if we can put a #value in a paticular cell or not 
def is_safe(n, r, c):     
  #checking in row     
  for i in range(0,SIZE):     
    #there is a cell with same value      
    if matrix[r][i] == n:        
      return False     
    #checking in column     
  for i in range(0,SIZE):     
    #there is a cell with same value        
    if matrix[i][c] == n:          
      return False     
  row_start = (r//3)*3     
  col_start = (c//3)*3;     
    #checking submatrix     
  for i in range(row_start,row_start+3):        
    for j in range(col_start,col_start+3):          
      if matrix[i][j]==n:
        return False     
  return True 
#function to check if we can put a #value in a paticular cell or not 
def solve_sudoku():
  row = 0
  col = 0 
  #if all cells are assigned then the sudoku is already solved  #pass by reference because number_unassigned will change 
  # the values of row and col
  a = number_unassigned(row, col)  
  if a[2] == 0:     
    return True
  row = a[0]  
  col = a[1]  #number between 1 to 9  
  for i in range(1,10): 
  #if we can assign i to the cell or not   #the cell is 
    matrix[row][col]   
    if is_safe(i, row, col):     
      matrix[row][col] = i     
      #backtracking     
      if solve_sudoku():
        return True 
    #f we can't proceed with this solution 
    #reassign the cell     
    matrix[row][col]=0   
  return False 
if solve_sudoku():   
  print_sudoku() 
else:   
  print("No solution")

[6, 5, 1, 8, 7, 3, 2, 9, 4]
[7, 4, 3, 2, 5, 9, 1, 6, 8]
[9, 8, 2, 1, 6, 4, 3, 5, 7]
[1, 2, 5, 4, 3, 6, 8, 7, 9]
[4, 3, 9, 5, 8, 7, 6, 1, 2]
[8, 6, 7, 9, 1, 2, 5, 4, 3]
[5, 7, 8, 3, 9, 1, 4, 2, 6]
[2, 1, 6, 7, 4, 8, 9, 3, 5]
[3, 9, 4, 6, 2, 5, 7, 8, 1]


**INFERENCE RULES**

In [44]:
global facts
global is_changed

is_changed = True
facts = [["vertebrate","duck"],["flying","duck"],["mammal","cat"]]

def assert_fact(fact):
    global facts
    global is_changed
    if not fact in facts:
        facts += [fact]
        is_changed = True

while is_changed:
    is_changed = False
    for A1 in facts:
        if A1[0] == "mammal":
            assert_fact(["vertebrate",A1[1]])
        if A1[0] == "vertebrate":
            assert_fact(["animal",A1[1]])
        if A1[0] == "vertebrate" and ["flying",A1[1]] in facts:
            assert_fact(["bird",A1[1]])

print(facts)

[['vertebrate', 'duck'], ['flying', 'duck'], ['mammal', 'cat'], ['animal', 'duck'], ['bird', 'duck'], ['vertebrate', 'cat'], ['animal', 'cat']]


**INFERENCE RULES**

In [45]:
global facts
global is_changed

is_changed = True
facts =[["plants","mango"],["eating","mango"],["seed","sprouts"]]

def assert_fact(fact):
    global facts
    global is_changed
    if not fact in facts:
        facts += [fact]
        is_changed = True

while is_changed:
    is_changed = False
    for A1 in facts:
        if A1[0] == "seed":
            assert_fact(["plant",A1[1]])
        if A1[0] == "plant":
            assert_fact(["fruit",A1[1]])
        if A1[0] == "plant" and ["eating",A1[1]] in facts:
            assert_fact(["human",A1[1]])

print(facts)

[['plants', 'mango'], ['eating', 'mango'], ['seed', 'sprouts'], ['plant', 'sprouts'], ['fruit', 'sprouts']]


**THIEVES IN FLOORS**

In [52]:
import random

floors={1,2,3,4,5}
a_lives_in={1,2,3,4}
b_lives_in={2,3,4,5}
c_lives_in={2,3,4}

check=True

while check:
  b=random.choice(tuple(b_lives_in))
  if b==2:
    c=b+2
    if c in c_lives_in:
      check=False

e=c-3
floors_occ={b,c,e}
a=a_lives_in-floors_occ
floors_occ.update(a)
d=floors-floors_occ
floors_occ

{1, 2, 3, 4}

**PROBABILITY OF DIAMONDS, QUEENS, FACE CARDS IN PACK OF CARDS**

In [47]:
def event_probability(event_outcomes,sample_space):
  probability=(event_outcomes/sample_space)*100
  return round(probability,1)

cards=52

diamonds=13
diamond_probability=event_probability(diamonds,cards)

face_cards=12
face_cards_probability=event_probability(face_cards,cards)

queen_of_diamonds=1
queen_of_diamond_probability=event_probability(queen_of_diamonds,cards)

print(diamond_probability,end='%\n')
print(face_cards_probability,end='%\n')
print(queen_of_diamond_probability,end='%\n')

25.0%
23.1%
1.9%


**MONTY HALL PROBLEM WITH 3 EGGS**

In [54]:
import random

def run_trail(switch_eggs,neggs=3):
  chosen_egg=random.randint(1,neggs)
  if switch_eggs:
    revealed_egg=3 if chosen_egg==2 else 2
    available_eggs=[dnum for dnum in range(1,neggs+1) if dnum not in (chosen_egg,revealed_egg)]
    chosen_egg=random.choice(available_eggs)
  return chosen_egg==1

def run_trails(ntrails,switch_eggs,neggs=3):
  nwins=0
  for i in range(ntrails):
    if run_trail(switch_eggs,neggs):
      nwins+=1
  return nwins

neggs,ntrails=3,10000
nwins_without_switch = run_trails(ntrails,False,neggs)
nwins_with_switch= run_trails(ntrails,True,neggs)
print("Monty Hall Problem with {} eggs".format(neggs))
print("Propertion of WINS without switching: {:.4f}".format(nwins_without_switch/ntrails))
print("Proportion of WINS with switching:.{:.4f}".format(nwins_with_switch/ntrails))

Monty Hall Problem with 3 eggs
Propertion of WINS without switching: 0.3302
Proportion of WINS with switching:.0.6754
